Enable roaming for the Huawei card
Signed-off-by: martin f. krafft <madduck@madduck.net>

diff --git a/cards/huawei_me906s b/cards/huawei_me906s
--- a/cards/huawei_me906s
+++ b/cards/huawei_me906s
@@ -15,6 +15,8 @@ set -eu
 # ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 # OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 
+ALLOW_ROAMING="${IF_WWAN_ALLOW_ROAMING:-0}"
+
 setup() {
   SERIAL_DEV=/dev/ttyUSB0
   CHAT_TIMEOUT=3
@@ -51,12 +53,32 @@ REG_MAXWAIT=120
 
 register() {
   verbose_end "started."
-  verbose_begin "Waiting for up to $REG_MAXWAIT seconds for network registration"
+  local roaming; roaming=disabled
+  is_true ${ALLOW_ROAMING} && roaming=enabled
+  verbose_begin "Waiting for up to $REG_MAXWAIT seconds for network registration (roaming: $roaming)"
   local i; i=0
   while [ $i -lt $REG_MAXWAIT ]; do
     i=$((i+1))
-    modemchat TIMEOUT 1 '' 'AT+CREG?' '+CREG: 0,1' && return
-    verbose_cont .
+    modemchat SAY "'abort on' failures are expected and indicate success:\n" \
+      ABORT '+CREG: 0,1' ABORT '+CREG: 0,5' TIMEOUT 1 \
+      '' 'AT+CREG?' '+CREG: 0,2'
+    case "$?" in
+      0) # still registering
+         sleep 1 && verbose_cont .;;
+      3) # no response, assume still registering
+         verbose_cont.;;
+      4) # abort on first condition, i.e. registered to home network
+         verbose_end "registered to home network"; return;;
+      5) # abort on second condition, i.e. registered to foreign network
+         if [ $roaming = enabled ]; then
+           verbose_end "failed (roaming disabled)."
+           return 1
+         else
+           verbose_end "registered to roaming network."
+           return 0
+         fi
+         ;;
+    esac
   done
   verbose_end "failed."
   fail "Network registration failed in $REG_MAXWAIT seconds"
